/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktra;

import java.io.IOException;
import java.net.InetAddress;
//import java.net.SocketException;
//import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;

/**
 *
 * @author PC
 */
public class client extends javax.swing.JFrame {

    /**
     * Creates new form client
     */
    public client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mahoa = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        HienThi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Settext = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Gettext = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        keytext = new javax.swing.JTextPane();
        HienThi1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mahoa.setText("Encrypt");
        mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahoaActionPerformed(evt);
            }
        });

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        HienThi.setColumns(20);
        HienThi.setRows(5);
        jScrollPane2.setViewportView(HienThi);

        Settext.setColumns(20);
        Settext.setRows(5);
        jScrollPane3.setViewportView(Settext);

        Gettext.setColumns(20);
        Gettext.setRows(5);
        jScrollPane4.setViewportView(Gettext);

        jScrollPane5.setViewportView(keytext);

        HienThi1.setText("Trả về :");

        label1.setText("Thuật toán mã hóa và giải mã Vigenere");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HienThi1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(mahoa)
                        .addGap(70, 70, 70)
                        .addComponent(send)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(label1)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(HienThi1)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 18, Short.MAX_VALUE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mahoa)
                            .addComponent(send))
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahoaActionPerformed
        // TODO add your handling code here:

        int rowsize = 26;
        int columnsize = 26;
        int vigneretable[][] = new int[26][26];
        for (int rows = 0; rows < rowsize; rows++) {
            for (int column = 0; column < columnsize; column++) {
                vigneretable[rows][column] = (rows + column) % 26;
            }
        }
        try {
            System.out.println("Enter the plainttext");
            String plaint = Gettext.getText();
            plaint = plaint.toUpperCase();
            System.out.println("Enter the key: ");
            String keychar = keytext.getText();
            keychar = keychar.toUpperCase();
            String cipher = "";
            int keyindex = 0;
            for (int index = 0; index < plaint.length(); index++) {
                char pChar = plaint.charAt(index);
                int asciiVal = (int) pChar;
                if (pChar == ' ') {
                    cipher += pChar;
                    continue;
                }
                if (asciiVal < 65 || asciiVal > 90) {
                    cipher += pChar;
                    continue;
                }
                int basicPlaintTextValue = ((int) pChar) - 65;
                char kChar = keychar.charAt(keyindex);
                int basicKeyValue = ((int) kChar) - 65;
                int tableEntry = vigneretable[basicPlaintTextValue][basicKeyValue];
                char cChar = (char) (tableEntry + 65);
                cipher += cChar;
                keyindex++;
                if (keyindex == keychar.length()) {
                    keyindex = 0;
                }
            }
            System.out.println("Cipher text is " + cipher);
            Settext.setText(cipher.toUpperCase());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Key phải là chữ!");
        }

    }//GEN-LAST:event_mahoaActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try {
            byte[] manga = keytext.getText().getBytes();
            byte[] mangb = Settext.getText().getBytes();
            
            InetAddress diachi = InetAddress.getByName("localhost");
            
            int port = 7777;
            
            DatagramPacket guia = new DatagramPacket(manga, manga.length, diachi, port);
            clientsocket.send(guia);
            
            DatagramPacket guib = new DatagramPacket(mangb, mangb.length, diachi, port);
            clientsocket.send(guib);
        } catch (IOException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_sendActionPerformed
    private char mahoa(char ch, int key) {
        if (Character.isLetter(ch)) {
            ch = (char) ('A' + (Character.toUpperCase(ch) - 'A' + key) % 26);
        }
        return ch;
    }

    /**
     * @param args the command line arguments
     */
    public void setTextCP2(String text) {

        HienThi.setText(text);
        //HienThi1.setText(text);
    }
    static DatagramSocket clientsocket;

    public static void main(String args[]) throws IOException {
       

        client client1 = new client();
        client1.setVisible(true);
        clientsocket = new DatagramSocket();

        System.out.println("kết nối server");
        // khai báo 2 mảng a và b để chưa dữ liệu gửi lên server

        byte nhantong[] = new byte[256];
        int len = nhantong.length;
        DatagramPacket nhantongab = new DatagramPacket(nhantong, len);
        clientsocket.receive(nhantongab);
        String tonga = (new String(nhantongab.getData(), 0, nhantongab.getLength())).trim();

        client1.setTextCP2(tonga);

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Gettext;
    private javax.swing.JTextArea HienThi;
    private javax.swing.JLabel HienThi1;
    private javax.swing.JTextArea Settext;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane keytext;
    private javax.swing.JLabel label1;
    private javax.swing.JButton mahoa;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
