/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktra;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class sever extends javax.swing.JFrame {

    /**
     * Creates new form sever
     */
    public sever() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Settext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Gettext = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        keytext = new javax.swing.JTextPane();
        GiaiMa = new javax.swing.JButton();
        Send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Thuật toán mã hóa và giải mã Vigenere");

        Settext.setColumns(20);
        Settext.setRows(5);
        jScrollPane1.setViewportView(Settext);

        Gettext.setColumns(20);
        Gettext.setRows(5);
        jScrollPane2.setViewportView(Gettext);

        jScrollPane3.setViewportView(keytext);

        GiaiMa.setText("Decrypt");
        GiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiaiMaActionPerformed(evt);
            }
        });

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(GiaiMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(Send)
                                .addGap(80, 80, 80))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(label1)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GiaiMa)
                            .addComponent(Send))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiaiMaActionPerformed
        // TODO add your handling code here:
        
          int rowsize = 26;
        int columnsize = 26;
        int vigneretable[][] = new int [26][26];
        for(int rows =0;rows < rowsize;rows++)
        {
            for(int column = 0;column < columnsize;column++)
            {
                vigneretable[rows][column]= (rows+column)%26;
            }
        }
        try
        {
            System.out.println("Enter the cipher text");
            String cipher = Settext.getText();
            System.out.println("Enter the key: ");
            String keychar = keytext.getText();
            keychar = keychar.toUpperCase();
            String plaint = "";
            int keyindex = 0;
            for( int index = 0;index < cipher.length();index++)
            {
                char pChar = cipher.charAt(index);
                int asciiVal = (int) pChar;
                if(pChar == ' ')
                {
                    plaint +=pChar;
                    continue;
                }
                if(asciiVal < 65 || asciiVal > 90)
                {
                    plaint += pChar;
                    continue;
                }
                int basicPlaintTextValue = ((int)pChar)-65;
                char kChar = keychar.charAt(keyindex);
                int basicKeyValue = ((int)kChar)-65;
                for(int i=0;i<columnsize;i++)
                {
                    if(vigneretable[basicKeyValue][i] == basicPlaintTextValue)
                    {
                        char potcChar = (char)(vigneretable[basicKeyValue][i]+65);
                        char potpChar = (char) (i+65);
                        plaint +=potpChar;
                    }
                }
                keyindex++;
                if(keyindex == keychar.length())
                {
                    keyindex = 0;
                }
            }
            System.out.println("plaint text is "+plaint);
            Gettext.setText(plaint.toUpperCase());
            Settext.setText(cipher.toUpperCase());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Key phải là chữ!");
        }

    }//GEN-LAST:event_GiaiMaActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        try {
            // TODO add your handling code here:
            String chuoi = Gettext.getText();
            HashMap<String, Integer> map = new HashMap<String, Integer>();
            for (char c : chuoi.toCharArray()) {
                if (map.containsKey(String.valueOf(c))) {
                    Integer value = map.get(String.valueOf(c));
                    map.put(String.valueOf(c), new Integer(value + 1));
                } else {
                    map.put(String.valueOf(c), 1);
                }
            }
            
            final int maxValue = Collections.max(map.values());
            String result = "";
            for (Map.Entry<String, Integer> entry : map.entrySet()) {
                if (entry.getValue() == maxValue) {
                    result += entry.getKey() + ",";
                }
            }
            
            String trave = "Kí tự xuất hiện nhiều nhất là :"+ result +" \n số lần xuất hiện của nó là : "  + maxValue;

            byte[] mangsolan = new byte[256];
            mangsolan = trave.getBytes();
            DatagramPacket guichuoi = new DatagramPacket(mangsolan, mangsolan.length, diachi, port);
            sc.send(guichuoi);
        } catch (IOException ex) {
            Logger.getLogger(sever.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_SendActionPerformed

   
     static InetAddress diachi = null;
    static int port = 0;
    static DatagramSocket sc = null;
    
    /**
     * @param args the command line arguments
     */
   
     public void setTextCP(String text){
        Settext.setText(text);
    }
     public void setTextCP2(String text){
        keytext.setText(text);
    }
    
    public static void main(String args[]) throws SocketException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         sever server = new sever();
       
              
        server.setVisible(true);
         
        
        /* Create and display the form */
      sc = new DatagramSocket(7777);
        System.out.println("Server đã sẵn sàng!!!");
        // tạo 2 mảng byte để nhận dữ liệu
        byte soa[] = new byte[256];
        byte sob[] = new byte[256];
        // tạo 2 biến chiều dài để nhận dữ liệu
        int len1 = soa.length;
        int len2 = sob.length;
        
        // datagrampacket nhận dữ liệu
        DatagramPacket soanhan = new DatagramPacket(soa, len1);
        sc.receive(soanhan);
        DatagramPacket sobnhan = new DatagramPacket(sob, len2);
        sc.receive(sobnhan);
         // tạo 2 biến string để đọc dữ liệu nhận sang string
        diachi = soanhan.getAddress();
        port = soanhan.getPort();
       String ssa,ssb;
       ssa = (new String(soanhan.getData(), 0, len1)).trim();
       ssb = (new String(sobnhan.getData(), 0, len2)).trim();
       server.setTextCP(ssb);
       server.setTextCP2(ssa);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Gettext;
    private javax.swing.JButton GiaiMa;
    private javax.swing.JButton Send;
    private javax.swing.JTextArea Settext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane keytext;
    private javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
